wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.10
    start_time: 1654519560
    t:
      1:
      - 1
      - 41
      2:
      - 1
      - 41
      3:
      - 13
      - 16
      4: 3.9.10
      5: 0.12.11
      8:
      - 3
      - 5
      9:
        2: CycleGAN-and-pix2pix
aspect_ratio:
  desc: null
  value: 1.0
batch_size:
  desc: null
  value: 1
checkpoints_dir:
  desc: null
  value: ./checkpoints
crop_size:
  desc: null
  value: 256
dataroot:
  desc: null
  value: datasets/xuejie/testA
dataset_mode:
  desc: null
  value: single
direction:
  desc: null
  value: AtoB
display_id:
  desc: null
  value: -1
display_winsize:
  desc: null
  value: 256
epoch:
  desc: null
  value: latest
eval:
  desc: null
  value: false
gpu_ids:
  desc: null
  value:
  - 0
init_gain:
  desc: null
  value: 0.02
init_type:
  desc: null
  value: normal
input_nc:
  desc: null
  value: 3
isTrain:
  desc: null
  value: false
load_iter:
  desc: null
  value: 0
load_size:
  desc: null
  value: 256
max_dataset_size:
  desc: null
  value: .inf
model:
  desc: null
  value: test
model_suffix:
  desc: null
  value: ''
n_layers_D:
  desc: null
  value: 3
name:
  desc: null
  value: horse2zebra_pretrained
ndf:
  desc: null
  value: 64
netD:
  desc: null
  value: basic
netG:
  desc: null
  value: resnet_9blocks
ngf:
  desc: null
  value: 64
no_dropout:
  desc: null
  value: true
no_flip:
  desc: null
  value: true
norm:
  desc: null
  value: instance
num_test:
  desc: null
  value: 50
num_threads:
  desc: null
  value: 0
output_nc:
  desc: null
  value: 3
phase:
  desc: null
  value: test
preprocess:
  desc: null
  value: resize_and_crop
results_dir:
  desc: null
  value: ./results/
serial_batches:
  desc: null
  value: true
suffix:
  desc: null
  value: ''
use_wandb:
  desc: null
  value: true
verbose:
  desc: null
  value: false
